### ISSUE TITLE
Return host() for default(), not unknown

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/target-lexicon#49]
Currently, the `Default` implementation for Triple is not very useful. I'd rather have it return the host triple instead of `unknown-unknown-unknown-unknown`.

I'd make this a PR instead of an issue, except I'm having trouble with the change and I don't know why:
```
$ git diff
diff --git a/src/triple.rs b/src/triple.rs
index fe96159..fad0c43 100644
--- a/src/triple.rs
+++ b/src/triple.rs
@@ -131,13 +131,7 @@ impl Triple {
 
 impl Default for Triple {
     fn default() -> Self {
-        Self {
-            architecture: Architecture::Unknown,
-            vendor: Vendor::Unknown,
-            operating_system: OperatingSystem::Unknown,
-            environment: Environment::Unknown,
-            binary_format: BinaryFormat::Unknown,
-        }
+        Triple::host()
     }
 }
$ cargo check
error[E0599]: no function or associated item named `host` found for type `triple::Triple` in the current scope
   --> src/triple.rs:134:17
    |
76  | pub struct Triple {
    | ----------------- function or associated item `host` not found for this
...
134 |         Triple::host()
    |                 ^^^^ function or associated item not found in `triple::Triple`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `target-lexicon`
```

I know `Triple` has a `host` function, I'm not sure why it's not showing up here.
```

**Comment by sunfishcode** [comment]
`triple.rs` is also included by the `build.rs` file, to help it detect the build host and generate the `Triple::host` function. In that context, it can't call `host` yet because it doesn't exist yet.

Can you say more about why you want `Default` to return the host? In Cranelift, being explicit about what code is host-aware and what code isn't helps us maintain and test compiler components to support cross compilation.

**Comment by jyn514** [comment]
> triple.rs is also included by the build.rs file, to help it detect the build host and generate the Triple::host function. In that context, it can't call host yet because it doesn't exist yet.

Gotcha, so this could be fixed by moving the impl to lib.rs instead?

> Can you say more about why you want Default to return the host? 

Sure, I have an Options struct in my compiler. Previously, I had `#[derive(Default)]`, which set all the fields appropriately if you didn't have strong opinions. Since the `Default` for `Triple` isn't very useful, I now have to implement Default manually for that struct.

Anecdotally, I also thought that `host()` was already what `default()` did and was very surprised when it wasn't, it took me a few minutes to track down where the error was coming from.

**Comment by sunfishcode** [comment]
> Gotcha, so this could be fixed by moving the impl to lib.rs instead?

It's in build.rs so that it can see the TARGET environment variable as it is set when targeting the host. At least some of this information can be queried for in the regular build through `#[cfg(...)]` constructs, but I don't know whether all of the information we need is available. Another option would be to move the `default` impl into the code generated by the build.rs file.

> I have an Options struct in my compiler. Previously, I had #[derive(Default)], which set all the fields appropriately if you didn't have strong opinions. Since the Default for Triple isn't very useful, I now have to implement Default manually for that struct.

> Anecdotally, I also thought that host() was already what default() did and was very surprised when it wasn't, it took me a few minutes to track down where the error was coming from.

That makes sense. Thinking about it more, I think the reason we even have a `Default` impl for `Triple` is just that we have `Default` impls for `Architecture`, `OperatingSystem`, etcl., and the reason we have those is that it kind of matches how triple parsing works -- you can omit some fields, and they default to "unknown". But outside of parsing, as you observe, this behavior isn't so intuitive.

I've now submitted #51 to propose a possible solution -- remove the `Default` implementations, and add a new `DefaultToHost`, which wraps a `Triple` and adds a `Default` implementation targeting the host, which you could use in your Options struct. That way, we still oblige users to explicitly opt into defaulting to the host, but it's easy to do. What do you think of this approach?

**Comment by jyn514** [comment]
> remove the Default implementations, and add a new DefaultToHost, which wraps a Triple and adds a Default implementation targeting the host, which you could use in your Options struct. That way, we still oblige users to explicitly opt into defaulting to the host, but it's easy to do.

That sounds reasonable, I hadn't thought about parsing. I do wonder whether `DefaultToHost` needs to be in target-lexicon directly, I could just as easily write it downstream in my crate. Maybe just remove the `Default` altogether to be clear there's no reasonable default that works for everyone?

**Comment by sunfishcode** [comment]
It's not a lot of code, and it seems like something people will frequently need, so my sense is to have target-lexicon provide it.
