### ISSUE TITLE
Consider setting a lower MSRV

### ISSUE THREAD

**Issue by jyn514** [bytecodealliance/target-lexicon#58]
Motivation: I want to use `saltwater` in bindgen (https://github.com/rust-lang/rust-bindgen/pull/1782), but it has an MSRV of 1.34, which `target-lexicon` doesn't compile with. It uses the following features not in 1.34:

- `#[nonexhaustive]`: this can be replaced with a `#[doc(hidden)] __Nonexhaustive` variant and documentation that the enum is nonexhaustive

```rust
error[E0658]: non exhaustive is an experimental feature (see issue #44109)
  --> src/data_model.rs:39:1
   |
39 | #[non_exhaustive]
   | ^^^^^^^^^^^^^^^^^
```

- `Self::variant`: this can be replaced with the explicit type name

```rust
error: enum variants on type aliases are experimental
  --> src/data_model.rs:15:13
   |
15 |             Self::U8 => 8,
   |             ^^^^^^^^
```

- `extern crate alloc` in build.rs: this can be replaced by `use std as alloc;` as long as the `std` feature is enabled. I don't need 1.34 support with `no_std`.

```rust
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> build.rs:12:1
   |
12 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^
```

I understand that most bytecodealliance projects aren't considered stable and therefore have no MSRV, but this would help me a lot, I'm willing to make the PRs myself.

**Comment by sunfishcode** [comment]
The `Self` and `alloc` issues seem reasonable to fix. Removing `#[nonexhaustive]` would be inconvenient; we added it because every time we bump our major version, we cause some of our downstream users to have to update in lock-step with other downstream users. While the proposed alternative here would also work, changing to it would be yet another major-version bump. Does https://github.com/rust-lang/rust-bindgen/pull/1782#issuecomment-647250406 mean that perhaps the minimum Rust version could be bumped instead? `nonexhaustive` would only need [Rust 1.40](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html).

**Comment by jyn514** [comment]
Hmm this would be unfortunate for me personally since the latest version of rust we have at work is 1.34 and I'd like to eventually use saltwater via bindgen on a work project. If this is hard to do for target-lexicon I might add some more hacks to make `sizeof()` opt-out for saltwater.

**Comment by sunfishcode** [comment]
Would it work to change `#[nonexhaustive]` to `#[cfg_attr(feature = rust_1_40, non_exhaustive)]`, and add `rust_1_40` as a default feature in Cargo.toml? And maybe even add a `#[cfg(not(feature = rust_1_40))] #[doc(hidden)]  __Nonexhaustive` too.

**Comment by jyn514** [comment]
Sure, that works for me. Good idea!
